FROM node:20-alpine

RUN apk add --no-cache vips-dev python3 make g++

WORKDIR /app

COPY package*.json ./
RUN npm install --omit=dev

COPY . .

RUN mkdir -p /app/uploads

EXPOSE 3000
CMD ["node", "server.js"]
